server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://jjeongdb.************.ap-northeast-2.rds.amazonaws.com/carrotERD?autoReconnect=true # 변경해주세요
    username: jjeong # 변경해주세요
    password: *********** # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql
